const $ = (id) => document.getElementById(id);
const money = (n) => `${n < 0 ? '-' : '+'}$${Math.abs(n).toFixed(2)}`;
const dollars = (n) => `$${n.toFixed(2)}`;
const number = (id) => { const value = parseFloat($(id).value); return Number.isFinite(value) ? value : null; };

function decimalOdds(value, format) {
  if (format === 'decimal') return value;
  return value >= 100 ? 1 + value / 100 : 1 + 100 / Math.abs(value);
}
function effectiveOdds(odds, format, boost) { const decimal = decimalOdds(odds, format); return 1 + (decimal - 1) * (1 + boost / 100); }
function formatOdds(value, format) { if(format==='decimal') return value.toFixed(2); const american=value>=2 ? `+${Math.round((value-1)*100)}` : `${Math.round(-100/(value-1))}`; return american; }
function updateBoostMath(side) { const odds=number(`odds-${side}`), boost=number(`boost-${side}`)??0, format=$(`format-${side}`).value, target=$(`boost-math-${side}`); if(odds===null || (format==='decimal'&&odds<=1) || (format==='american'&&Math.abs(odds)<100)){ target.textContent='Enter valid odds to preview boosted odds'; return; } const base=decimalOdds(odds,format), multiplier=1+boost/100, effective=1+(base-1)*multiplier; const baseDisplay=format==='decimal'?base.toFixed(2):`${odds>0?'+':''}${odds}`; target.textContent=format==='decimal'?`${baseDisplay} → (${base.toFixed(2)} − 1) × ${multiplier.toFixed(2)} + 1 = ${effective.toFixed(2)} effective odds`:`${baseDisplay} → (${base.toFixed(2)} − 1) × ${multiplier.toFixed(2)} + 1 = ${formatOdds(effective,format)} effective odds`; }
function roundTo(value, increment) { return Math.round((value + Number.EPSILON) / increment) * increment; }
function candidate(a, b, oa, ob, increment) {
  const total = a + b; const payoutA = a * oa; const payoutB = b * ob;
  return { a, b, total, payoutA, payoutB, profitA:payoutA-total, profitB:payoutB-total, score:Math.min(payoutA-total, payoutB-total), roundedA:roundTo(a,increment), roundedB:roundTo(b,increment) };
}
function calculate(data) {
  const oa = effectiveOdds(data.oddsA,data.formatA,data.boostA); const ob = effectiveOdds(data.oddsB,data.formatB,data.boostB);
  const arbScore = 1/oa + 1/ob; const maxA = Math.min(...[data.maxBoostA,data.maxStakeA,data.bankroll].filter(v=>v !== null)); const maxB = Math.min(...[data.maxBoostB,data.maxStakeB,data.bankroll].filter(v=>v !== null));
  const candidates = [{a:maxA,b:maxA*oa/ob},{a:maxB*ob/oa,b:maxB},{a:maxA,b:maxB}].filter(x=>x.a>=0&&x.b>=0&&x.a<=maxA+1e-8&&x.b<=maxB+1e-8&&(!data.bankroll||x.a+x.b<=data.bankroll+1e-8));
  let best = null; for (const raw of candidates) { const c = candidate(raw.a,raw.b,oa,ob,data.rounding); for (const da of [-1,0,1]) for (const db of [-1,0,1]) { const a=Math.max(0,c.roundedA+da*data.rounding), b=Math.max(0,c.roundedB+db*data.rounding); if(a<=maxA+1e-8&&b<=maxB+1e-8&&(!data.bankroll||a+b<=data.bankroll+1e-8)){ const tested=candidate(a,b,oa,ob,data.rounding); if(!best||tested.score>best.score) best=tested; } } }
  return {...best,oa,ob,arbScore,exists:arbScore<1};
}
function readData() { return { bookA:$('book-a').value||'Book A',bookB:$('book-b').value||'Book B',outcomeA:$('outcome-a').value||'Outcome A',outcomeB:$('outcome-b').value||'Outcome B',formatA:$('format-a').value,formatB:$('format-b').value,oddsA:number('odds-a'),oddsB:number('odds-b'),boostA:number('boost-a')??0,boostB:number('boost-b')??0,maxBoostA:number('max-boost-a'),maxBoostB:number('max-boost-b'),maxStakeA:number('max-stake-a'),maxStakeB:number('max-stake-b'),bankroll:number('bankroll'),rounding:parseFloat($('rounding').value)}; }
function validate(d) { if(d.oddsA===null||d.oddsB===null) return 'Enter odds for both sides.'; if(d.formatA==='decimal'&&d.oddsA<=1 || d.formatB==='decimal'&&d.oddsB<=1) return 'Decimal odds must be greater than 1.00.'; if(d.formatA==='american'&&Math.abs(d.oddsA)<100 || d.formatB==='american'&&Math.abs(d.oddsB)<100) return 'American odds must be at least +100 or -100.'; if([d.boostA,d.boostB,d.maxBoostA,d.maxBoostB,d.maxStakeA,d.maxStakeB,d.bankroll].some(v=>v!==null&&v<0)) return 'Boosts and stake limits cannot be negative.'; return ''; }
function render(d,r) { $('results').hidden=false; $('result-title').textContent=r.exists?'Opportunity found':'No protected edge at these numbers'; $('arb-badge').textContent=r.exists?'Mathematical arbitrage':'No arbitrage'; $('arb-badge').classList.toggle('no-arb',!r.exists); $('guaranteed-profit').textContent=money(r.score); $('guaranteed-profit').className=r.score>=0?'':'negative'; $('roi').textContent=`${(r.score/r.total*100).toFixed(2)}%`; $('arb-score').textContent=`Arb score ${r.arbScore.toFixed(4)}`; $('stake-a').textContent=dollars(r.a); $('stake-b').textContent=dollars(r.b); $('total-stake').textContent=dollars(r.total); $('result-book-a').textContent=d.bookA; $('result-book-b').textContent=d.bookB; updateBookLogo('book-a','analysis-logo-a'); updateBookLogo('book-b','analysis-logo-b'); $('result-outcome-a').textContent=d.outcomeA; $('result-outcome-b').textContent=d.outcomeB; $('effective-a').textContent=`Effective odds ${r.oa.toFixed(3)}`; $('effective-b').textContent=`Effective odds ${r.ob.toFixed(3)}`; $('table-outcome-a').textContent=`${d.outcomeA} wins`; $('table-outcome-b').textContent=`${d.outcomeB} wins`; $('payout-a').textContent=dollars(r.payoutA); $('payout-b').textContent=dollars(r.payoutB); $('profit-a').textContent=money(r.profitA); $('profit-b').textContent=money(r.profitB); $('profit-a').className=r.profitA>=0?'positive':'negative'; $('profit-b').className=r.profitB>=0?'positive':'negative'; $('math-a-label').textContent=`If ${d.outcomeA} wins`; $('math-b-label').textContent=`If ${d.outcomeB} wins`; $('math-a-payout').textContent=`${dollars(r.a)} × ${r.oa.toFixed(3)} = ${dollars(r.payoutA)} gross payout`; $('math-b-payout').textContent=`${dollars(r.b)} × ${r.ob.toFixed(3)} = ${dollars(r.payoutB)} gross payout`; $('math-a-profit').textContent=`${dollars(r.payoutA)} − ${dollars(r.total)} total stake = ${money(r.profitA)}`; $('math-b-profit').textContent=`${dollars(r.payoutB)} − ${dollars(r.total)} total stake = ${money(r.profitB)}`; const warnings=['Verify both wagers refer to exactly the same event and mutually exclusive outcomes.','Verify overtime, push, cancellation, and postponement rules match.','Verify each profit boost applies to this market and displayed stake.','For player props, verify participation, DNP, void, and stat-correction rules.']; $('warnings').innerHTML=warnings.map(x=>`<li>${x}</li>`).join(''); $('results').scrollIntoView({behavior:'smooth',block:'start'}); }
const bookLogoData = {'FanDuel':['assets/logos/fanduel-app.jpg','FD'],'DraftKings':['assets/logos/draftkings-app.jpg','DK'],'BetMGM':[null,'M'],'Caesars Sportsbook':[null,'C'],'bet365':['assets/logos/bet365.svg','365'],'ESPN BET':['assets/logos/espn.svg','E'],'PrizePicks':[null,'P'],'Underdog':[null,'U'],'Kalshi':[null,'K'],'Polymarket':[null,'P'],'Other sportsbook':[null,'•']};
function updateBookLogo(selectId,logoId) { const [src,mark]=bookLogoData[$(selectId).value]||[null,'•']; const logo=$(logoId); const isAnalysis=logoId.startsWith('analysis-'); logo.className=`${isAnalysis?'analysis-logo':'book-logo'} logo-generic`; logo.textContent=mark; if(!src)return; const image=document.createElement('img'); image.src=src; image.alt=''; image.addEventListener('error',()=>{ image.remove(); logo.textContent=mark; }); logo.textContent=''; logo.appendChild(image); }
['a','b'].forEach(side => { $(`book-${side}`).addEventListener('change',()=>updateBookLogo(`book-${side}`,`logo-${side}`)); updateBookLogo(`book-${side}`,`logo-${side}`); });
function setupBookPicker(side) { const picker=document.querySelector(`[data-book-picker="${side}"]`), select=$(`book-${side}`), menu=$(`book-menu-${side}`), trigger=$(`book-trigger-${side}`); [...select.options].forEach(option=>{ const item=document.createElement('button'); item.type='button'; item.className='book-option'; item.setAttribute('role','option'); item.dataset.value=option.value; const [src,mark]=bookLogoData[option.value]||[null,'•']; item.innerHTML=`<span class="book-logo ${src?'':'logo-generic'}">${src?`<img src="${src}" alt="">`:mark}</span><span>${option.textContent}</span>`; item.addEventListener('click',()=>{ select.value=option.value; $(`book-label-${side}`).textContent=option.textContent; updateBookLogo(`book-${side}`,`logo-${side}`); [...menu.children].forEach(child=>child.setAttribute('aria-selected',child===item?'true':'false')); picker.classList.remove('is-open'); trigger.setAttribute('aria-expanded','false'); select.dispatchEvent(new Event('change',{bubbles:true})); }); menu.appendChild(item); }); trigger.addEventListener('click',()=>{ const open=picker.classList.toggle('is-open'); trigger.setAttribute('aria-expanded',String(open)); }); }
['a','b'].forEach(setupBookPicker);
document.addEventListener('click',(event)=>document.querySelectorAll('.book-picker.is-open').forEach(picker=>{if(!picker.contains(event.target)){picker.classList.remove('is-open'); const trigger=picker.querySelector('.book-trigger'); trigger.setAttribute('aria-expanded','false');}}));
['a','b'].forEach(side => ['odds','boost','format'].forEach(field => { $(`${field}-${side}`).addEventListener('input',()=>updateBoostMath(side)); $(`${field}-${side}`).addEventListener('change',()=>updateBoostMath(side)); }));
['a','b'].forEach(updateBoostMath);
$('calculator-form').addEventListener('submit',(event)=>{ event.preventDefault(); const d=readData(), error=validate(d); $('error-message').hidden=!error; $('error-message').textContent=error; if(error)return; render(d,calculate(d)); });
