const $ = (id) => document.getElementById(id);
const money = (n) => `${n < 0 ? '-' : '+'}$${Math.abs(n).toFixed(2)}`;
const dollars = (n) => `$${n.toFixed(2)}`;
const number = (id) => { const value = parseFloat($(id).value); return Number.isFinite(value) ? value : null; };

function decimalOdds(value, format) {
  if (format === 'decimal') return value;
  return value >= 100 ? 1 + value / 100 : 1 + 100 / Math.abs(value);
}
function effectiveOdds(odds, format, boost) { const decimal = decimalOdds(odds, format); return 1 + (decimal - 1) * (1 + boost / 100); }
function formatOdds(value, format) { if(format==='decimal') return value.toFixed(2); const american=value>=2 ? `+${Math.round((value-1)*100)}` : `${Math.round(-100/(value-1))}`; return american; }
function updateBoostMath(side) { const odds=number(`odds-${side}`), odds2=number(`odds-${side}-2`), boost=number(`boost-${side}`)??0, format=$(`format-${side}`).value, target=$(`boost-math-${side}`); if(odds===null||odds2===null||(format==='decimal'&&(odds<=1||odds2<=1))||(format==='american'&&(Math.abs(odds)<100||Math.abs(odds2)<100))){ target.textContent='Boosted odds: — / —'; return; } target.textContent=`Boosted odds: ${formatOdds(effectiveOdds(odds,format,boost),format)} / ${formatOdds(effectiveOdds(odds2,format,boost),format)}`; }
function roundTo(value, increment) { return Math.round((value + Number.EPSILON) / increment) * increment; }
function candidate(a, b, oa, ob, increment) {
  const total = a + b; const payoutA = a * oa; const payoutB = b * ob;
  return { a, b, total, payoutA, payoutB, profitA:payoutA-total, profitB:payoutB-total, score:Math.min(payoutA-total, payoutB-total), roundedA:roundTo(a,increment), roundedB:roundTo(b,increment) };
}
function calculate(data) {
  const oa = effectiveOdds(data.oddsA,data.formatA,data.boostA); const ob = effectiveOdds(data.oddsB2,data.formatB,data.boostB);
  const arbScore = 1/oa + 1/ob; const maxA = Math.min(...[data.maxBoostA,data.maxStakeA,data.bankroll].filter(v=>v !== null)); const maxB = Math.min(...[data.maxBoostB,data.maxStakeB,data.bankroll].filter(v=>v !== null));
  const candidates = [{a:maxA,b:maxA*oa/ob},{a:maxB*ob/oa,b:maxB},{a:maxA,b:maxB}].filter(x=>x.a>=0&&x.b>=0&&x.a<=maxA+1e-8&&x.b<=maxB+1e-8&&(!data.bankroll||x.a+x.b<=data.bankroll+1e-8));
  let best = null; for (const raw of candidates) { const c = candidate(raw.a,raw.b,oa,ob,data.rounding); for (const da of [-1,0,1]) for (const db of [-1,0,1]) { const a=Math.max(0,c.roundedA+da*data.rounding), b=Math.max(0,c.roundedB+db*data.rounding); if(a<=maxA+1e-8&&b<=maxB+1e-8&&(!data.bankroll||a+b<=data.bankroll+1e-8)){ const tested=candidate(a,b,oa,ob,data.rounding); if(!best||tested.score>best.score) best=tested; } } }
  return {...best,oa,ob,arbScore,exists:arbScore<1};
}
// Compare the two valid cross-market pairings. Same-outcome pairings are not
// hedges, so only A-at-book-1 + B-at-book-2 and B-at-book-1 + A-at-book-2
// are evaluated.
function comparePairings(book1, book2, constraints = {}) {
  const pairings = [
    { id:'book1-a-book2-b', label:`${book1.name}: ${book1.outcomeA} + ${book2.name}: ${book2.outcomeB}`, first:book1.outcomeA, second:book2.outcomeB, oddsA:book1.oddsA, oddsB:book2.oddsB, formatA:book1.formatA, formatB:book2.formatB, boostA:book1.boostA||0, boostB:book2.boostB||0, maxA:book1.maxA, maxB:book2.maxB },
    { id:'book1-b-book2-a', label:`${book1.name}: ${book1.outcomeB} + ${book2.name}: ${book2.outcomeA}`, first:book1.outcomeB, second:book2.outcomeA, oddsA:book1.oddsB, oddsB:book2.oddsA, formatA:book1.formatB, formatB:book2.formatA, boostA:book1.boostB||0, boostB:book2.boostA||0, maxA:book1.maxB, maxB:book2.maxA }
  ];
  return pairings.map(pair => { const oa=effectiveOdds(pair.oddsA,pair.formatA,pair.boostA), ob=effectiveOdds(pair.oddsB,pair.formatB,pair.boostB), arbScore=1/oa+1/ob; return {...pair,oa,ob,arbScore,arbitrageExists:arbScore<1, margin:1-arbScore, constraints}; }).sort((a,b)=>b.margin-a.margin);
}
function readData() { return { bookA:$('book-a').value||'Book A',bookB:$('book-b').value||'Book B',outcomeA:$('outcome-a').value||'Outcome A',outcomeB:$('outcome-b').value||'Outcome B',outcomeA2:$('outcome-a-2').value||'Outcome B',outcomeB2:$('outcome-b-2').value||'Outcome A',formatA:$('format-a').value,formatB:$('format-b').value,oddsA:number('odds-a'),oddsB:number('odds-b'),oddsA2:number('odds-a-2'),oddsB2:number('odds-b-2'),boostA:number('boost-a')??0,boostB:number('boost-b')??0,boostA2:number('boost-a')??0,boostB2:number('boost-b')??0,maxBoostA:number('max-boost-a'),maxBoostB:number('max-boost-b'),maxStakeA:number('max-stake-a'),maxStakeB:number('max-stake-b'),bankroll:number('bankroll'),rounding:parseFloat($('rounding').value)}; }
function validate(d) { if([d.oddsA,d.oddsB,d.oddsA2,d.oddsB2].some(v=>v===null)) return 'Enter odds for both outcomes at both sportsbooks.'; if(d.formatA==='decimal'&&[d.oddsA,d.oddsA2].some(v=>v<=1) || d.formatB==='decimal'&&[d.oddsB,d.oddsB2].some(v=>v<=1)) return 'Decimal odds must be greater than 1.00.'; if(d.formatA==='american'&&[d.oddsA,d.oddsA2].some(v=>Math.abs(v)<100) || d.formatB==='american'&&[d.oddsB,d.oddsB2].some(v=>Math.abs(v)<100)) return 'American odds must be at least +100 or -100.'; if([d.boostA,d.boostB,d.boostA2,d.boostB2,d.maxBoostA,d.maxBoostB,d.maxStakeA,d.maxStakeB,d.bankroll].some(v=>v!==null&&v<0)) return 'Boosts and stake limits cannot be negative.'; return ''; }
function render(d,r) { $('results').hidden=false; $('result-title').textContent=r.exists?'Opportunity found':'No protected edge at these numbers'; $('arb-badge').textContent=r.exists?'Mathematical arbitrage':'No arbitrage'; $('arb-badge').classList.toggle('no-arb',!r.exists); $('guaranteed-profit').textContent=money(r.score); $('guaranteed-profit').className=r.score>=0?'':'negative'; $('roi').textContent=`${(r.score/r.total*100).toFixed(2)}%`; $('arb-score').textContent=`Arb score ${r.arbScore.toFixed(4)}`; $('stake-a').textContent=dollars(r.a); $('stake-b').textContent=dollars(r.b); $('total-stake').textContent=dollars(r.total); $('result-book-a').textContent=d.bookA; $('result-book-b').textContent=d.bookB; updateBookLogo('book-a','analysis-logo-a'); updateBookLogo('book-b','analysis-logo-b'); $('result-outcome-a').textContent=d.outcomeA; $('result-outcome-b').textContent=d.outcomeB; $('effective-a').textContent=`Effective odds ${r.oa.toFixed(3)}`; $('effective-b').textContent=`Effective odds ${r.ob.toFixed(3)}`; $('table-outcome-a').textContent=`${d.outcomeA} wins`; $('table-outcome-b').textContent=`${d.outcomeB} wins`; $('payout-a').textContent=dollars(r.payoutA); $('payout-b').textContent=dollars(r.payoutB); $('profit-a').textContent=money(r.profitA); $('profit-b').textContent=money(r.profitB); $('profit-a').className=r.profitA>=0?'positive':'negative'; $('profit-b').className=r.profitB>=0?'positive':'negative'; $('math-a-label').textContent=`If ${d.outcomeA} wins`; $('math-b-label').textContent=`If ${d.outcomeB} wins`; $('math-a-payout').textContent=`${dollars(r.a)} × ${r.oa.toFixed(3)} = ${dollars(r.payoutA)} gross payout`; $('math-b-payout').textContent=`${dollars(r.b)} × ${r.ob.toFixed(3)} = ${dollars(r.payoutB)} gross payout`; $('math-a-profit').textContent=`${dollars(r.payoutA)} − ${dollars(r.total)} total stake = ${money(r.profitA)}`; $('math-b-profit').textContent=`${dollars(r.payoutB)} − ${dollars(r.total)} total stake = ${money(r.profitB)}`; const warnings=['Verify both wagers refer to exactly the same event and mutually exclusive outcomes.','Verify overtime, push, cancellation, and postponement rules match.','Verify each profit boost applies to this market and displayed stake.','For player props, verify participation, DNP, void, and stat-correction rules.']; $('warnings').innerHTML=warnings.map(x=>`<li>${x}</li>`).join(''); $('results').scrollIntoView({behavior:'smooth',block:'start'}); }
const bookLogoData = {'FanDuel':['assets/logos/fanduel-app.jpg','FD'],'DraftKings':['assets/logos/draftkings-app.jpg','DK'],'BetMGM':[null,'M'],'Caesars Sportsbook':[null,'C'],'bet365':['assets/logos/bet365.svg','365'],'ESPN BET':['assets/logos/espn.svg','E'],'PrizePicks':[null,'P'],'Underdog':[null,'U'],'Kalshi':[null,'K'],'Polymarket':[null,'P'],'Other sportsbook':[null,'•']};
function updateBookLogo(selectId,logoId) { const [src,mark]=bookLogoData[$(selectId).value]||[null,'•']; const logo=$(logoId); const isAnalysis=logoId.startsWith('analysis-'); logo.className=`${isAnalysis?'analysis-logo':'book-logo'} logo-generic`; logo.textContent=mark; if(!src)return; const image=document.createElement('img'); image.src=src; image.alt=''; image.addEventListener('error',()=>{ image.remove(); logo.textContent=mark; }); logo.textContent=''; logo.appendChild(image); }
['a','b'].forEach(side => { $(`book-${side}`).addEventListener('change',()=>updateBookLogo(`book-${side}`,`logo-${side}`)); updateBookLogo(`book-${side}`,`logo-${side}`); });
function setupBookPicker(side) { const picker=document.querySelector(`[data-book-picker="${side}"]`), select=$(`book-${side}`), menu=$(`book-menu-${side}`), trigger=$(`book-trigger-${side}`); [...select.options].forEach(option=>{ const item=document.createElement('button'); item.type='button'; item.className='book-option'; item.setAttribute('role','option'); item.dataset.value=option.value; const [src,mark]=bookLogoData[option.value]||[null,'•']; item.innerHTML=`<span class="book-logo ${src?'':'logo-generic'}">${src?`<img src="${src}" alt="">`:mark}</span><span>${option.textContent}</span>`; item.addEventListener('click',()=>{ select.value=option.value; $(`book-label-${side}`).textContent=option.textContent; $(`book-title-${side}`).textContent=option.textContent; updateBookLogo(`book-${side}`,`logo-${side}`); [...menu.children].forEach(child=>child.setAttribute('aria-selected',child===item?'true':'false')); picker.classList.remove('is-open'); trigger.setAttribute('aria-expanded','false'); select.dispatchEvent(new Event('change',{bubbles:true})); }); menu.appendChild(item); }); trigger.addEventListener('click',()=>{ const open=picker.classList.toggle('is-open'); trigger.setAttribute('aria-expanded',String(open)); }); }
['a','b'].forEach(setupBookPicker);
document.addEventListener('click',(event)=>document.querySelectorAll('.book-picker.is-open').forEach(picker=>{if(!picker.contains(event.target)){picker.classList.remove('is-open'); const trigger=picker.querySelector('.book-trigger'); trigger.setAttribute('aria-expanded','false');}}));
['a','b'].forEach(side => ['odds','boost','format'].forEach(field => { $(`${field}-${side}`).addEventListener('input',()=>updateBoostMath(side)); $(`${field}-${side}`).addEventListener('change',()=>updateBoostMath(side)); }));
['a','b'].forEach(updateBoostMath);
function mirrorField(sourceId,targetId) { const source=$(sourceId), target=$(targetId); if(!source||!target)return; source.addEventListener('input',()=>{ target.value=source.value; }); source.addEventListener('change',()=>{ target.value=source.value; }); }
mirrorField('outcome-a','outcome-b'); mirrorField('outcome-a-2','outcome-b-2');
document.querySelectorAll('.info-button').forEach(button=>button.addEventListener('click',()=>{ const side=button.dataset.infoSide, format=$(`format-${side}`).value, boost=number(`boost-${side}`)??0, first=number(`odds-${side}`), second=number(`odds-${side}-2`), preview=$(`boosted-preview-${side}`); if(first===null||second===null){ preview.textContent='Enter both odds'; preview.hidden=false; return; } const multiplier=(1+boost/100).toFixed(2); const firstBase=decimalOdds(first,format), secondBase=decimalOdds(second,format); preview.textContent=`(${firstBase.toFixed(2)}−1)×${multiplier}+1=${formatOdds(effectiveOdds(first,format,boost),format)} · (${secondBase.toFixed(2)}−1)×${multiplier}+1=${formatOdds(effectiveOdds(second,format,boost),format)}`; preview.hidden=!preview.hidden; }));
const resetDefaults={a:{book:'FanDuel',outcome:'Outcome A',outcome2:'Outcome B',odds:'',odds2:'',boost:'0',maxBoost:'',maxStake:''},b:{book:'DraftKings',outcome:'Outcome A',outcome2:'Outcome B',odds:'',odds2:'',boost:'0',maxBoost:'',maxStake:''}};
document.querySelectorAll('.reset-book').forEach(button=>button.addEventListener('click',()=>{ const side=button.dataset.resetSide, defaults=resetDefaults[side], select=$(`book-${side}`); select.value=defaults.book; $(`book-label-${side}`).textContent=defaults.book; $(`book-title-${side}`).textContent=defaults.book; updateBookLogo(`book-${side}`,`logo-${side}`); $(`outcome-${side}`).value=defaults.outcome; $(`outcome-${side}-2`).value=defaults.outcome2; $(`odds-${side}`).value=defaults.odds; $(`odds-${side}-2`).value=defaults.odds2; $(`boost-${side}`).value=defaults.boost; $(`max-boost-${side}`).value=defaults.maxBoost; $(`max-stake-${side}`).value=defaults.maxStake; updateBoostMath(side); const preview=$(`boosted-preview-${side}`); preview.hidden=true; document.querySelectorAll(`#book-menu-${side} .book-option`).forEach(item=>item.setAttribute('aria-selected',item.dataset.value===defaults.book?'true':'false')); }));
function renderPairings(d) { const pairings=comparePairings({name:d.bookA,outcomeA:d.outcomeA,outcomeB:d.outcomeA2,oddsA:d.oddsA,oddsB:d.oddsA2,formatA:d.formatA,formatB:d.formatA,boostA:d.boostA,boostB:d.boostA},{name:d.bookB,outcomeA:d.outcomeB,outcomeB:d.outcomeB2,oddsA:d.oddsB,oddsB:d.oddsB2,formatA:d.formatB,formatB:d.formatB,boostA:d.boostB,boostB:d.boostB}); $('pairing-results').innerHTML=pairings.map((pair,index)=>`<div class="pairing-row ${index===0?'recommended':''}"><span class="pairing-label">${index===0?'<span class="pairing-tag">Recommended</span>':''}${pair.label}</span><strong>${pair.arbitrageExists?'Arb '+(pair.margin*100).toFixed(2)+'%':'No arb'}</strong><span class="muted">Score ${pair.arbScore.toFixed(4)}</span></div>`).join(''); }
$('calculator-form').addEventListener('submit',(event)=>{ event.preventDefault(); const d=readData(), error=validate(d); $('error-message').hidden=!error; $('error-message').textContent=error; if(error)return; const resultData={...d,outcomeB:d.outcomeB2}; render(resultData,calculate(d)); renderPairings(d); });
