const $ = (id) => document.getElementById(id);
const money = (n) => `${n < 0 ? '-' : '+'}$${Math.abs(n).toFixed(2)}`;
const dollars = (n) => `$${n.toFixed(2)}`;
const number = (id) => { const value = parseFloat($(id).value); return Number.isFinite(value) ? value : null; };
function animateProfit(target,value) { if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){ target.textContent=money(value); return; } const started=performance.now(), duration=720, sign=value<0?'-':'+'; const tick=(now)=>{ const progress=Math.min((now-started)/duration,1), eased=1-Math.pow(1-progress,3), current=value*eased; target.textContent=`${sign}$${Math.abs(current).toFixed(2)}`; if(progress<1)requestAnimationFrame(tick); }; target.textContent=money(0); requestAnimationFrame(tick); }

function decimalOdds(value, format) {
  if (format === 'decimal') return value;
  return value >= 100 ? 1 + value / 100 : 1 + 100 / Math.abs(value);
}
function effectiveOdds(odds, format, boost) { const decimal = decimalOdds(odds, format); return 1 + (decimal - 1) * (1 + boost / 100); }
function formatOdds(value, format) { if(format==='decimal') return value.toFixed(2); const american=value>=2 ? `+${Math.round((value-1)*100)}` : `${Math.round(-100/(value-1))}`; return american; }
function updateBoostMath(side) { const odds=number(`odds-${side}`), odds2=number(`odds-${side}-2`), boost=number(`boost-${side}`)??0, format=$(`format-${side}`).value, firstTarget=$(`boosted-${side}-1`), secondTarget=$(`boosted-${side}-2`); const valid=(value)=>value!==null&&(format==='decimal'?value>1:Math.abs(value)>=100); const firstValid=valid(odds), secondValid=valid(odds2); firstTarget.textContent=firstValid?formatOdds(effectiveOdds(odds,format,boost),format):'—'; secondTarget.textContent=secondValid?formatOdds(effectiveOdds(odds2,format,boost),format):'—'; [firstTarget,secondTarget].filter((target,index)=>index===0?firstValid:secondValid).forEach(target=>{ target.classList.remove('updated'); void target.offsetWidth; target.classList.add('updated'); }); }
function roundTo(value, increment) { return Math.round((value + Number.EPSILON) / increment) * increment; }
function candidate(a, b, oa, ob, increment) {
  const total = a + b; const payoutA = a * oa; const payoutB = b * ob;
  return { a, b, total, payoutA, payoutB, profitA:payoutA-total, profitB:payoutB-total, score:Math.min(payoutA-total, payoutB-total), roundedA:roundTo(a,increment), roundedB:roundTo(b,increment) };
}
function calculate(data) {
  const oa = effectiveOdds(data.oddsA,data.formatA,data.boostA); const ob = effectiveOdds(data.oddsB2,data.formatB,data.boostB);
  const arbScore = 1/oa + 1/ob; const sizingLimits=[data.maxBoostA,data.maxBoostB,data.maxStakeA,data.maxStakeB,data.bankroll].filter(v=>v !== null); if(!sizingLimits.length) return {...candidate(0,0,oa,ob,data.rounding),oa,ob,arbScore,exists:arbScore<1,needsSizing:true}; const maxA = Math.min(...[data.maxBoostA,data.maxStakeA,data.bankroll].filter(v=>v !== null)); const maxB = Math.min(...[data.maxBoostB,data.maxStakeB,data.bankroll].filter(v=>v !== null));
  if(data.mode==='protect') { const favoredA=data.favoredOutcome==='a', hedgeOdds=favoredA?ob:oa, hedgeRate=hedgeOdds-1, favoredLimit=favoredA?maxA:maxB, hedgeLimit=favoredA?maxB:maxA, bankrollLimit=data.bankroll===null?Infinity:(data.bankroll*hedgeRate+data.maxLoss)/(hedgeRate+1), hedgeCapLimit=hedgeLimit*hedgeRate+data.maxLoss, favoredStake=Math.max(0,Math.min(favoredLimit,bankrollLimit,hedgeCapLimit)), hedgeStake=Math.max(0,(favoredStake-data.maxLoss)/hedgeRate), protectedCandidate=favoredA?{a:favoredStake,b:hedgeStake}:{a:hedgeStake,b:favoredStake}; const protectedResult=candidate(protectedCandidate.a,protectedCandidate.b,oa,ob,data.rounding); return {...protectedResult,score:favoredA?protectedResult.profitA:protectedResult.profitB,oa,ob,arbScore,exists:false,needsSizing:false,protected:true}; }
  const candidates = [{a:maxA,b:maxA*oa/ob},{a:maxB*ob/oa,b:maxB},{a:maxA,b:maxB},...(data.bankroll!==null?[{a:data.bankroll*ob/(oa+ob),b:data.bankroll*oa/(oa+ob)}]:[])].filter(x=>x.a>=0&&x.b>=0&&x.a<=maxA+1e-8&&x.b<=maxB+1e-8&&(data.bankroll===null||x.a+x.b<=data.bankroll+1e-8));
  let best = null; for (const raw of candidates) { const c = candidate(raw.a,raw.b,oa,ob,data.rounding); for (const da of [-1,0,1]) for (const db of [-1,0,1]) { const a=Math.max(0,c.roundedA+da*data.rounding), b=Math.max(0,c.roundedB+db*data.rounding); if(a<=maxA+1e-8&&b<=maxB+1e-8&&(!data.bankroll||a+b<=data.bankroll+1e-8)){ const tested=candidate(a,b,oa,ob,data.rounding); if(!best||tested.score>best.score) best=tested; } } }
  if(!best) { best=candidate(0,0,oa,ob,data.rounding); }
  return {...best,oa,ob,arbScore,exists:arbScore<1};
}
// Compare the two valid cross-market pairings. Same-outcome pairings are not
// hedges, so only A-at-book-1 + B-at-book-2 and B-at-book-1 + A-at-book-2
// are evaluated.
function comparePairings(book1, book2, constraints = {}) {
  const pairings = [
    { id:'book1-a-book2-b', label:`${book1.name}: ${book1.outcomeA} + ${book2.name}: ${book2.outcomeB}`, first:book1.outcomeA, second:book2.outcomeB, oddsA:book1.oddsA, oddsB:book2.oddsB, formatA:book1.formatA, formatB:book2.formatB, boostA:book1.boostA||0, boostB:book2.boostB||0, maxA:book1.maxA, maxB:book2.maxB },
    { id:'book1-b-book2-a', label:`${book1.name}: ${book1.outcomeB} + ${book2.name}: ${book2.outcomeA}`, first:book1.outcomeB, second:book2.outcomeA, oddsA:book1.oddsB, oddsB:book2.oddsA, formatA:book1.formatB, formatB:book2.formatA, boostA:book1.boostB||0, boostB:book2.boostA||0, maxA:book1.maxB, maxB:book2.maxA }
  ];
  return pairings.map(pair => { const oa=effectiveOdds(pair.oddsA,pair.formatA,pair.boostA), ob=effectiveOdds(pair.oddsB,pair.formatB,pair.boostB), arbScore=1/oa+1/ob; return {...pair,oa,ob,arbScore,arbitrageExists:arbScore<1, margin:1-arbScore, constraints}; }).sort((a,b)=>b.margin-a.margin);
}
function readMarkets() { return [...document.querySelectorAll('.panel-a .market-group')].map((group,index)=>{ const other=document.querySelectorAll('.panel-b .market-group')[index], rows=(root)=>[...root.querySelectorAll('.outcome-row')].map(row=>row.querySelectorAll('input')); const rowsA=rows(group), rowsB=rows(other); const value=(root,selector,fallback='')=>root?.querySelector(selector)?.value||fallback; return { name:value(group,'.market-name input',`Market ${index+1}`), outcomeA:rowsA[0]?.[0]?.value||'Outcome A', oddsA:parseFloat(rowsA[0]?.[1]?.value), outcomeA2:rowsA[1]?.[0]?.value||'Outcome B', oddsA2:parseFloat(rowsA[1]?.[1]?.value), formatA:value(group,'select','american'), outcomeB:rowsB[0]?.[0]?.value||'Outcome A', oddsB:parseFloat(rowsB[0]?.[1]?.value), outcomeB2:rowsB[1]?.[0]?.value||'Outcome B', oddsB2:parseFloat(rowsB[1]?.[1]?.value), formatB:value(other,'select','american')}; }); }
function readData() { const markets=readMarkets(); const first=markets[0]||{}; return { bookA:$('book-a').value||'Book A',bookB:$('book-b').value||'Book B',marketName:first.name||'Market 1',outcomeA:first.outcomeA||'Outcome A',outcomeB:first.outcomeB||'Outcome A',outcomeA2:first.outcomeA2||'Outcome B',outcomeB2:first.outcomeB2||'Outcome B',formatA:first.formatA||$('format-a').value,formatB:first.formatB||$('format-b').value,oddsA:Number.isFinite(first.oddsA)?first.oddsA:number('odds-a'),oddsB:Number.isFinite(first.oddsB)?first.oddsB:number('odds-b'),oddsA2:Number.isFinite(first.oddsA2)?first.oddsA2:number('odds-a-2'),oddsB2:Number.isFinite(first.oddsB2)?first.oddsB2:number('odds-b-2'),boostA:number('boost-a')??0,boostB:number('boost-b')??0,boostA2:number('boost-a')??0,boostB2:number('boost-b')??0,maxBoostA:number('max-boost-a'),maxBoostB:number('max-boost-b'),maxStakeA:number('max-stake-a'),maxStakeB:number('max-stake-b'),bankroll:number('bankroll'),rounding:parseFloat($('rounding').value),mode:$('strategy-mode')?.dataset.mode||'guarantee',favoredOutcome:$('favored-outcome')?.value||'a',maxLoss:number('max-loss')??0,markets}; }
function validate(d) { if([d.oddsA,d.oddsB,d.oddsA2,d.oddsB2].some(v=>v===null)) return 'Enter odds for both outcomes at both sportsbooks.'; if(d.formatA==='decimal'&&[d.oddsA,d.oddsA2].some(v=>v<=1) || d.formatB==='decimal'&&[d.oddsB,d.oddsB2].some(v=>v<=1)) return 'Decimal odds must be greater than 1.00.'; if(d.formatA==='american'&&[d.oddsA,d.oddsA2].some(v=>Math.abs(v)<100) || d.formatB==='american'&&[d.oddsB,d.oddsB2].some(v=>Math.abs(v)<100)) return 'American odds must be at least +100 or -100.'; if([d.boostA,d.boostB,d.boostA2,d.boostB2,d.maxBoostA,d.maxBoostB,d.maxStakeA,d.maxStakeB,d.bankroll].some(v=>v!==null&&v<0)) return 'Boosts and stake limits cannot be negative.'; return ''; }
function render(d,r) { $('results').hidden=false; $('result-title').textContent=r.exists?'Opportunity found':'No protected edge at these numbers'; $('arb-badge').textContent=r.exists?'Mathematical arbitrage':'No arbitrage'; $('arb-badge').classList.toggle('no-arb',!r.exists); $('guaranteed-profit').textContent=money(r.score); $('guaranteed-profit').className=r.score>=0?'':'negative'; $('roi').textContent=r.total?`${(r.score/r.total*100).toFixed(2)}%`:'—'; $('arb-score').textContent=`Arb score ${r.arbScore.toFixed(4)}`; $('stake-a').textContent=dollars(r.a); $('stake-b').textContent=dollars(r.b); $('total-stake').textContent=dollars(r.total); $('result-book-a').textContent=d.bookA; $('result-book-b').textContent=d.bookB; $('boost-used-a').textContent=`${d.boostA}% boost used`; $('boost-used-b').textContent=`${d.boostB}% boost used`; updateBookLogo('book-a','analysis-logo-a'); updateBookLogo('book-b','analysis-logo-b'); updateBookLogo('book-a','stake-logo-a'); updateBookLogo('book-b','stake-logo-b'); $('result-outcome-a').textContent=d.outcomeA; $('result-outcome-b').textContent=d.outcomeB; $('effective-a').textContent=`Effective odds ${formatOdds(r.oa,d.formatA)}`; $('effective-b').textContent=`Effective odds ${formatOdds(r.ob,d.formatB)}`; $('table-outcome-a').textContent=`${d.outcomeA} wins`; $('table-outcome-b').textContent=`${d.outcomeB} wins`; $('payout-a').textContent=dollars(r.payoutA); $('payout-b').textContent=dollars(r.payoutB); $('profit-a').textContent=money(r.profitA); $('profit-b').textContent=money(r.profitB); $('profit-a').className=r.profitA>=0?'positive':'negative'; $('profit-b').className=r.profitB>=0?'positive':'negative'; $('math-a-label').textContent=`If ${d.outcomeA} wins`; $('math-b-label').textContent=`If ${d.outcomeB} wins`; $('math-a-payout').textContent=`${dollars(r.a)} × ${r.oa.toFixed(3)} = ${dollars(r.payoutA)} gross payout`; $('math-b-payout').textContent=`${dollars(r.b)} × ${r.ob.toFixed(3)} = ${dollars(r.payoutB)} gross payout`; $('math-a-profit').textContent=`${dollars(r.payoutA)} − ${dollars(r.total)} total stake = ${money(r.profitA)}`; $('math-b-profit').textContent=`${dollars(r.payoutB)} − ${dollars(r.total)} total stake = ${money(r.profitB)}`; const warnings=['Verify both wagers refer to exactly the same event and mutually exclusive outcomes.','Verify overtime, push, cancellation, and postponement rules match.','Verify each profit boost applies to this market and displayed stake.','For player props, verify participation, DNP, void, and stat-correction rules.']; $('warnings').innerHTML=warnings.map(x=>`<li>${x}</li>`).join(''); $('results').scrollIntoView({behavior:'smooth',block:'start'}); }
const baseRender=render; render=(d,r)=>{ baseRender(d,r); $('result-outcome-a').textContent=`${d.marketName||'Market 1'} · ${d.outcomeA}`; $('result-outcome-b').textContent=`${d.marketName||'Market 1'} · ${d.outcomeB}`; if(r.protected){ $('result-title').textContent='Protection plan'; $('arb-badge').textContent='Favored-outcome protection'; $('arb-badge').classList.remove('no-arb'); $('guaranteed-profit').previousElementSibling.textContent='Favored outcome net profit'; $('arb-score').textContent='Downside protection mode'; } };
const bookLogoData = {'FanDuel':['assets/logos/fanduel-app.jpg','FD'],'DraftKings':['assets/logos/draftkings-app.jpg','DK'],'BetMGM':[null,'M'],'Caesars Sportsbook':[null,'C'],'bet365':['assets/logos/bet365.svg','365'],'ESPN BET':['assets/logos/espn.svg','E'],'PrizePicks':[null,'P'],'Underdog':[null,'U'],'Kalshi':[null,'K'],'Polymarket':[null,'P'],'Other sportsbook':[null,'•']};
function updateBookLogo(selectId,logoId) { const [src,mark]=bookLogoData[$(selectId).value]||[null,'•']; const logo=$(logoId); const isAnalysis=logoId.startsWith('analysis-'); logo.className=`${isAnalysis?'analysis-logo':'book-logo'} logo-generic`; logo.textContent=mark; if(!src)return; const image=document.createElement('img'); image.src=src; image.alt=''; image.addEventListener('error',()=>{ image.remove(); logo.textContent=mark; }); logo.textContent=''; logo.appendChild(image); }
['a','b'].forEach(side => { $(`book-${side}`).addEventListener('change',()=>updateBookLogo(`book-${side}`,`logo-${side}`)); updateBookLogo(`book-${side}`,`logo-${side}`); });
function setupBookPicker(side) { const picker=document.querySelector(`[data-book-picker="${side}"]`), select=$(`book-${side}`), menu=$(`book-menu-${side}`), trigger=$(`book-trigger-${side}`); [...select.options].forEach(option=>{ const item=document.createElement('button'); item.type='button'; item.className='book-option'; item.setAttribute('role','option'); item.dataset.value=option.value; const [src,mark]=bookLogoData[option.value]||[null,'•']; item.innerHTML=`<span class="book-logo ${src?'':'logo-generic'}">${src?`<img src="${src}" alt="">`:mark}</span><span>${option.textContent}</span>`; item.addEventListener('click',()=>{ select.value=option.value; $(`book-label-${side}`).textContent=option.textContent; updateBookLogo(`book-${side}`,`logo-${side}`); [...menu.children].forEach(child=>child.setAttribute('aria-selected',child===item?'true':'false')); picker.classList.remove('is-open'); trigger.setAttribute('aria-expanded','false'); select.dispatchEvent(new Event('change',{bubbles:true})); }); menu.appendChild(item); }); trigger.addEventListener('click',()=>{ const open=picker.classList.toggle('is-open'); trigger.setAttribute('aria-expanded',String(open)); }); }
['a','b'].forEach(setupBookPicker);
document.addEventListener('click',(event)=>document.querySelectorAll('.book-picker.is-open').forEach(picker=>{if(!picker.contains(event.target)){picker.classList.remove('is-open'); const trigger=picker.querySelector('.book-trigger'); trigger.setAttribute('aria-expanded','false');}}));
['a','b'].forEach(side => { ['odds','boost','format'].forEach(field => { $(`${field}-${side}`).addEventListener('input',()=>updateBoostMath(side)); $(`${field}-${side}`).addEventListener('change',()=>updateBoostMath(side)); }); $(`odds-${side}-2`).addEventListener('input',()=>updateBoostMath(side)); $(`odds-${side}-2`).addEventListener('change',()=>updateBoostMath(side)); });
['a','b'].forEach(updateBoostMath);
function mirrorField(sourceId,targetId) { const source=$(sourceId), target=$(targetId); if(!source||!target)return; source.addEventListener('input',()=>{ target.value=source.value; }); source.addEventListener('change',()=>{ target.value=source.value; }); }
mirrorField('outcome-a','outcome-b'); mirrorField('outcome-b','outcome-a'); mirrorField('outcome-a-2','outcome-b-2'); mirrorField('outcome-b-2','outcome-a-2');
document.querySelectorAll('.info-button').forEach(button=>button.addEventListener('click',()=>{ const side=button.dataset.infoSide, format=$(`format-${side}`).value, boost=number(`boost-${side}`)??0, first=number(`odds-${side}`), second=number(`odds-${side}-2`), preview=$(`boosted-preview-${side}`); if(first===null||second===null){ preview.textContent='Enter both odds'; preview.hidden=false; return; } const multiplier=(1+boost/100).toFixed(2); const firstBase=decimalOdds(first,format), secondBase=decimalOdds(second,format); preview.innerHTML=`<span>Outcome A: (${firstBase.toFixed(2)} − 1) × ${multiplier} + 1 = ${formatOdds(effectiveOdds(first,format,boost),format)}</span><span>Outcome B: (${secondBase.toFixed(2)} − 1) × ${multiplier} + 1 = ${formatOdds(effectiveOdds(second,format,boost),format)}</span>`; preview.hidden=!preview.hidden; }));
function addMarketGroup(side,index) { const panel=document.querySelector(`.panel-${side}`), source=[...panel.querySelectorAll('.market-group')].at(-1), clone=source.cloneNode(true); clone.querySelectorAll('.remove-market').forEach(button=>button.remove()); clone.dataset.marketIndex=index; clone.querySelectorAll('[id]').forEach(element=>{ element.id=`${element.id}-market-${index}`; }); clone.querySelectorAll('input').forEach(input=>{ if(input.closest('.market-name')) input.value=`Market ${index}`; else if(input.closest('.outcome-row')&&input.closest('.field')?.querySelector('span')?.textContent.startsWith('Outcome')) input.value=input.value; else if(input.type!=='hidden') input.value=''; }); clone.querySelectorAll('select').forEach(select=>{ select.value=source.querySelector('select')?.value||'american'; }); clone.querySelectorAll('.boosted-value').forEach(output=>output.textContent='—'); clone.querySelectorAll('.boosted-preview').forEach(preview=>{ preview.textContent=''; preview.hidden=true; }); const remove=document.createElement('button'); remove.type='button'; remove.className='remove-market'; remove.textContent='Remove market'; remove.addEventListener('click',()=>{ const groups=document.querySelectorAll(`.market-group[data-market-index="${index}"]`); groups.forEach(group=>group.classList.add('market-removing')); window.setTimeout(()=>groups.forEach(group=>group.remove()),320); }); clone.appendChild(remove); source.insertAdjacentElement('afterend',clone); requestAnimationFrame(()=>clone.classList.add('market-enter')); return clone; }
function bindMarketPair(index) { const groupA=document.querySelectorAll('.panel-a .market-group')[index], groupB=document.querySelectorAll('.panel-b .market-group')[index]; if(!groupA||!groupB)return; const nameA=groupA.querySelector('.market-name input'), nameB=groupB.querySelector('.market-name input'); nameA.addEventListener('input',()=>{ nameB.value=nameA.value; }); nameB.addEventListener('input',()=>{ nameA.value=nameB.value; }); [...groupA.querySelectorAll('.outcome-row')].forEach((row,rowIndex)=>{ const inputA=row.querySelector('.field input'), inputB=groupB.querySelectorAll('.outcome-row')[rowIndex]?.querySelector('.field input'); if(!inputA||!inputB)return; inputA.addEventListener('input',()=>{ inputB.value=inputA.value; }); inputB.addEventListener('input',()=>{ inputA.value=inputB.value; }); }); }
const marketButtonA=$('add-market'), marketButtonB=marketButtonA.cloneNode(true); marketButtonB.removeAttribute('id'); document.querySelector('.panel-b .market-group').insertAdjacentElement('afterend',marketButtonB); bindMarketPair(0); document.querySelectorAll('.add-market').forEach(button=>button.addEventListener('click',()=>{ const next=document.querySelectorAll('.panel-a .market-group').length+1; addMarketGroup('a',next); addMarketGroup('b',next); bindMarketPair(next-1); }));
document.querySelectorAll('.market-name input').forEach(input=>{ input.placeholder='Moneyline, Spread, Total, etc.'; if(input.value==='Market 1')input.value=''; });
function refreshMarketHints() { document.querySelectorAll('.market-name input').forEach(input=>{ input.placeholder='Moneyline, Spread, Total, etc.'; if(/^Market \d+$/.test(input.value))input.value=''; }); }
document.querySelectorAll('.add-market').forEach(button=>button.addEventListener('click',()=>window.setTimeout(refreshMarketHints,0)));
const resetDefaults={a:{book:'FanDuel',outcome:'Outcome A',outcome2:'Outcome B',odds:'',odds2:'',boost:'0',maxBoost:'',maxStake:''},b:{book:'DraftKings',outcome:'Outcome A',outcome2:'Outcome B',odds:'',odds2:'',boost:'0',maxBoost:'',maxStake:''}};
document.querySelectorAll('.reset-book').forEach(button=>button.addEventListener('click',()=>{ const side=button.dataset.resetSide, defaults=resetDefaults[side], select=$(`book-${side}`); select.value=defaults.book; $(`book-label-${side}`).textContent=defaults.book; updateBookLogo(`book-${side}`,`logo-${side}`); $(`outcome-${side}`).value=defaults.outcome; $(`outcome-${side}-2`).value=defaults.outcome2; $(`odds-${side}`).value=defaults.odds; $(`odds-${side}-2`).value=defaults.odds2; $(`boost-${side}`).value=defaults.boost; $(`max-boost-${side}`).value=defaults.maxBoost; $(`max-stake-${side}`).value=defaults.maxStake; updateBoostMath(side); const preview=$(`boosted-preview-${side}`); preview.hidden=true; document.querySelectorAll(`#book-menu-${side} .book-option`).forEach(item=>item.setAttribute('aria-selected',item.dataset.value===defaults.book?'true':'false')); }));
function pairingList(d) { const markets=d.markets?.length?d.markets:[{name:d.marketName,outcomeA:d.outcomeA,outcomeA2:d.outcomeA2,outcomeB:d.outcomeB,outcomeB2:d.outcomeB2,oddsA:d.oddsA,oddsA2:d.oddsA2,oddsB:d.oddsB,oddsB2:d.oddsB2,formatA:d.formatA,formatB:d.formatB}]; return markets.flatMap((market,index)=>comparePairings({name:d.bookA,outcomeA:market.outcomeA,outcomeB:market.outcomeA2,oddsA:market.oddsA,oddsB:market.oddsA2,formatA:market.formatA,formatB:market.formatA,boostA:d.boostA,boostB:d.boostA},{name:d.bookB,outcomeA:market.outcomeB,outcomeB:market.outcomeB2,oddsA:market.oddsB,oddsB:market.oddsB2,formatA:market.formatB,formatB:market.formatB,boostA:d.boostB,boostB:d.boostB}).map(pair=>{ const id=`market-${index}-${pair.id}`, data=pairingData({...d,markets},id), result=calculate(data); return {...pair,id,marketIndex:index,marketName:market.name,result}; })).sort((a,b)=>(b.result?.score??-Infinity)-(a.result?.score??-Infinity)); }
function pairingData(d,pairingId) { const match=pairingId.match(/^market-(\d+)-(book1-a-book2-b|book1-b-book2-a)$/), marketIndex=match?Number(match[1]):0, reverse=match?match[2]==='book1-b-book2-a':pairingId==='book1-b-book2-a', market=d.markets?.[marketIndex]; if(!market)return d; return {...d,marketName:market.name,outcomeA:reverse?market.outcomeA2:market.outcomeA,outcomeB:reverse?market.outcomeB:market.outcomeB2,oddsA:reverse?market.oddsA2:market.oddsA,oddsB2:reverse?market.oddsB:market.oddsB2,formatA:reverse?market.formatA:market.formatA,formatB:reverse?market.formatB:market.formatB,boostA:d.boostA,boostB:d.boostB}; }
function renderPairings(d,selectedId=pairingList(d)[0]?.id) { const pairings=pairingList(d); $('pairing-results').innerHTML=pairings.map((pair,index)=>{ const result=pair.result, roi=result.total?`${(result.score/result.total*100).toFixed(2)}% ROI`:result.needsSizing?'Needs sizing':'—'; return `<button type="button" class="pairing-row ${pair.id===selectedId?'selected':''} ${index===0?'recommended':''}" data-pairing-id="${pair.id}" aria-pressed="${pair.id===selectedId}"><span class="pairing-label">${index===0?'<span class="pairing-tag">Recommended</span>':''}<span>${pair.marketName||'Market 1'} · ${pair.label}</span></span><strong>${result.total?money(result.score):result.needsSizing?'—':'No profit'}</strong><span class="muted">${roi}</span></button>`; }).join(''); document.querySelectorAll('#pairing-results .pairing-row').forEach(row=>row.addEventListener('click',()=>{ const next=pairingData(d,row.dataset.pairingId), result=calculate(next); window.activePairingId=row.dataset.pairingId; render(next,result); if(!result.total) $('roi').textContent='—'; animateProfit($('guaranteed-profit'),result.score); renderPairings(d,row.dataset.pairingId); $('result-note').textContent=result.needsSizing?'Arbitrage detected. Add a bankroll or stake limit to size the protected position.':result.exists?'The hedge holds after rounding — both outcomes land in the green.':'No protected profit after rounding. Try different odds or limits.'; $('hero-result').classList.toggle('locked',result.exists&&!result.needsSizing); })); }
$('pairing-toggle').addEventListener('click',()=>{ const button=$('pairing-toggle'), panel=button.closest('.pairing-panel'), collapsed=panel.classList.toggle('is-collapsed'); button.setAttribute('aria-expanded',String(!collapsed)); button.setAttribute('aria-label',`${collapsed?'Expand':'Collapse'} pairing comparison`); });
$('calculator-form').addEventListener('submit',(event)=>{ event.preventDefault(); const d=readData(), error=validate(d); $('error-message').hidden=!error; $('error-message').textContent=error; if(error)return; const selectedId=pairingList(d)[0]?.id; window.activePairingId=selectedId; const resultData=pairingData(d,selectedId), result=calculate(resultData); render(resultData,result); if(!result.total) $('roi').textContent='—'; animateProfit($('guaranteed-profit'),result.score); renderPairings(d,selectedId); $('result-note').textContent=result.needsSizing?'Arbitrage detected. Add a bankroll or stake limit to size the protected position.':result.protected?'The favored outcome keeps its upside while the other outcome stays within your loss limit.':result.exists?'The hedge holds after rounding — both outcomes land in the green.':'No protected profit after rounding. Try different odds or limits.'; $('hero-result').classList.toggle('locked',result.exists&&!result.needsSizing); });


const shareFieldIds=['book-a','boost-a','max-boost-a','max-stake-a','format-a','outcome-a','odds-a','outcome-a-2','odds-a-2','book-b','boost-b','max-boost-b','max-stake-b','format-b','outcome-b','odds-b','outcome-b-2','odds-b-2','bankroll','rounding'];
function readShareState(){ return {...Object.fromEntries(shareFieldIds.map(id=>[id,$(id)?.value??''])),markets:readMarkets().map(market=>({name:market.name,outcomeA:market.outcomeA,oddsA:Number.isFinite(market.oddsA)?market.oddsA:'',outcomeA2:market.outcomeA2,oddsA2:Number.isFinite(market.oddsA2)?market.oddsA2:'',outcomeB:market.outcomeB,oddsB:Number.isFinite(market.oddsB)?market.oddsB:'',outcomeB2:market.outcomeB2,oddsB2:Number.isFinite(market.oddsB2)?market.oddsB2:'',formatA:market.formatA,formatB:market.formatB}))}; }
function bytesToBase64(bytes){ let binary=''; bytes.forEach(byte=>{ binary+=String.fromCharCode(byte); }); return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
function base64ToBytes(value){ const binary=atob(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4)); return Uint8Array.from(binary,character=>character.charCodeAt(0)); }
async function compressShareState(state){ const stream=new Blob([JSON.stringify(state)]).stream().pipeThrough(new CompressionStream('gzip')); return bytesToBase64(new Uint8Array(await new Response(stream).arrayBuffer())); }
async function decompressShareState(value){ const stream=new Blob([base64ToBytes(value)]).stream().pipeThrough(new DecompressionStream('gzip')); return JSON.parse(await new Response(stream).text()); }
async function shareUrl(){ const state=readShareState(); if(typeof CompressionStream==='undefined') return `${window.location.href.split('#')[0]}#share=${encodeURIComponent(JSON.stringify(state))}`; const encoded=await compressShareState(state); return `${window.location.href.split('#')[0]}#share=gz:${encoded}`; }
async function restoreShareState(){ const match=window.location.hash.match(/^#share=(.+)$/); if(!match)return; let state; try{ state=match[1].startsWith('gz:')?await decompressShareState(match[1].slice(3)):JSON.parse(decodeURIComponent(match[1])); }catch{return;} const markets=state.markets||[]; while(document.querySelectorAll('.panel-a .market-group').length<markets.length) $('add-market').click(); shareFieldIds.forEach(id=>{ if($(id)&&Object.prototype.hasOwnProperty.call(state,id))$(id).value=state[id]; }); markets.forEach((market,index)=>{ ['a','b'].forEach(side=>{ const group=document.querySelectorAll(`.panel-${side} .market-group`)[index], prefix=side==='a'?'A':'B'; if(!group)return; group.querySelector('.market-name input').value=market.name; const rows=group.querySelectorAll('.outcome-row'), names=side==='a'?[market.outcomeA,market.outcomeA2]:[market.outcomeB,market.outcomeB2], odds=side==='a'?[market.oddsA,market.oddsA2]:[market.oddsB,market.oddsB2]; rows.forEach((row,rowIndex)=>{ const inputs=row.querySelectorAll('input'); inputs[0].value=names[rowIndex]; inputs[1].value=odds[rowIndex]; }); group.querySelector('select').value=market[`format${prefix}`]; }); }); ['a','b'].forEach(side=>{ $(`book-label-${side}`).textContent=$(`book-${side}`).selectedOptions[0]?.textContent||$('book-'+side).value; updateBookLogo(`book-${side}`,`logo-${side}`); updateBoostMath(side); }); window.activePairingId=null; }
restoreShareState();
$('share-button').addEventListener('click',async()=>{ const url=await shareUrl(), status=$('share-status'); try{ await navigator.clipboard.writeText(url); status.textContent='Share link copied'; }catch{ status.textContent='Copy this link: '+url; } window.history.replaceState(null,'',url); window.setTimeout(()=>{status.textContent='';},4000); });
const strategyMode=$('strategy-mode'); strategyMode.addEventListener('click',()=>{ const protect=strategyMode.dataset.mode!=='protect'; strategyMode.dataset.mode=protect?'protect':'guarantee'; strategyMode.setAttribute('aria-checked',String(protect)); strategyMode.classList.toggle('is-protect',protect); strategyMode.querySelector('strong').textContent=protect?'Protection Mode':'Guarantee Mode'; strategyMode.querySelector('small').textContent=protect?'Cap downside on a favored outcome':'Balance both outcomes'; document.querySelectorAll('.favored-field').forEach(field=>field.hidden=!protect); });
